version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile  # используем обычный Dockerfile для разработки
    ports:
      - "8080:8080"
    command: make dev
    volumes:
      - .:/app